name: Docker Image CI

on:
  push:
    branches: [ dev ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login Docker Hub
      env: 
        DOCKER_LOGIN: andrurevkach
        DOCKER_PASSWORD: Andru1998
      run: | 
        docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build ./server -t andrurevkach/server_part:latest 
    - name: Push in Docker Hub
      run: | 
        docker push andrurevkach/server_part:latest
